// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.ada.federate.rpc;

public final class RPCService {
  private RPCService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:federate.HelloRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string endpoint = 1;</code>
     * @return A list containing the endpoint.
     */
    java.util.List<java.lang.String>
        getEndpointList();
    /**
     * <code>repeated string endpoint = 1;</code>
     * @return The count of endpoint.
     */
    int getEndpointCount();
    /**
     * <code>repeated string endpoint = 1;</code>
     * @param index The index of the element to return.
     * @return The endpoint at the given index.
     */
    java.lang.String getEndpoint(int index);
    /**
     * <code>repeated string endpoint = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the endpoint at the given index.
     */
    com.google.protobuf.ByteString
        getEndpointBytes(int index);

    /**
     * <code>required int32 siloId = 2;</code>
     * @return Whether the siloId field is set.
     */
    boolean hasSiloId();
    /**
     * <code>required int32 siloId = 2;</code>
     * @return The siloId.
     */
    int getSiloId();

    /**
     * <code>required int32 round = 5;</code>
     * @return Whether the round field is set.
     */
    boolean hasRound();
    /**
     * <code>required int32 round = 5;</code>
     * @return The round.
     */
    int getRound();

    /**
     * <pre>
     * 密钥生成
     *  required string p = 5;
     *  required string g = 6;
     *  required string publicKey = 7;
     * </pre>
     *
     * <code>required int32 index = 6;</code>
     * @return Whether the index field is set.
     */
    boolean hasIndex();
    /**
     * <pre>
     * 密钥生成
     *  required string p = 5;
     *  required string g = 6;
     *  required string publicKey = 7;
     * </pre>
     *
     * <code>required int32 index = 6;</code>
     * @return The index.
     */
    int getIndex();
  }
  /**
   * Protobuf type {@code federate.HelloRequest}
   */
  public static final class HelloRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:federate.HelloRequest)
      HelloRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloRequest.newBuilder() to construct.
    private HelloRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloRequest() {
      endpoint_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HelloRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                endpoint_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              endpoint_.add(bs);
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              siloId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000002;
              round_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000004;
              index_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          endpoint_ = endpoint_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ada.federate.rpc.RPCService.internal_static_federate_HelloRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ada.federate.rpc.RPCService.internal_static_federate_HelloRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ada.federate.rpc.RPCService.HelloRequest.class, com.ada.federate.rpc.RPCService.HelloRequest.Builder.class);
    }

    private int bitField0_;
    public static final int ENDPOINT_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList endpoint_;
    /**
     * <code>repeated string endpoint = 1;</code>
     * @return A list containing the endpoint.
     */
    public com.google.protobuf.ProtocolStringList
        getEndpointList() {
      return endpoint_;
    }
    /**
     * <code>repeated string endpoint = 1;</code>
     * @return The count of endpoint.
     */
    public int getEndpointCount() {
      return endpoint_.size();
    }
    /**
     * <code>repeated string endpoint = 1;</code>
     * @param index The index of the element to return.
     * @return The endpoint at the given index.
     */
    public java.lang.String getEndpoint(int index) {
      return endpoint_.get(index);
    }
    /**
     * <code>repeated string endpoint = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the endpoint at the given index.
     */
    public com.google.protobuf.ByteString
        getEndpointBytes(int index) {
      return endpoint_.getByteString(index);
    }

    public static final int SILOID_FIELD_NUMBER = 2;
    private int siloId_;
    /**
     * <code>required int32 siloId = 2;</code>
     * @return Whether the siloId field is set.
     */
    @java.lang.Override
    public boolean hasSiloId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 siloId = 2;</code>
     * @return The siloId.
     */
    @java.lang.Override
    public int getSiloId() {
      return siloId_;
    }

    public static final int ROUND_FIELD_NUMBER = 5;
    private int round_;
    /**
     * <code>required int32 round = 5;</code>
     * @return Whether the round field is set.
     */
    @java.lang.Override
    public boolean hasRound() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 round = 5;</code>
     * @return The round.
     */
    @java.lang.Override
    public int getRound() {
      return round_;
    }

    public static final int INDEX_FIELD_NUMBER = 6;
    private int index_;
    /**
     * <pre>
     * 密钥生成
     *  required string p = 5;
     *  required string g = 6;
     *  required string publicKey = 7;
     * </pre>
     *
     * <code>required int32 index = 6;</code>
     * @return Whether the index field is set.
     */
    @java.lang.Override
    public boolean hasIndex() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 密钥生成
     *  required string p = 5;
     *  required string g = 6;
     *  required string publicKey = 7;
     * </pre>
     *
     * <code>required int32 index = 6;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSiloId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRound()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < endpoint_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, endpoint_.getRaw(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(2, siloId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(5, round_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(6, index_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < endpoint_.size(); i++) {
          dataSize += computeStringSizeNoTag(endpoint_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getEndpointList().size();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, siloId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, round_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, index_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ada.federate.rpc.RPCService.HelloRequest)) {
        return super.equals(obj);
      }
      com.ada.federate.rpc.RPCService.HelloRequest other = (com.ada.federate.rpc.RPCService.HelloRequest) obj;

      if (!getEndpointList()
          .equals(other.getEndpointList())) return false;
      if (hasSiloId() != other.hasSiloId()) return false;
      if (hasSiloId()) {
        if (getSiloId()
            != other.getSiloId()) return false;
      }
      if (hasRound() != other.hasRound()) return false;
      if (hasRound()) {
        if (getRound()
            != other.getRound()) return false;
      }
      if (hasIndex() != other.hasIndex()) return false;
      if (hasIndex()) {
        if (getIndex()
            != other.getIndex()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEndpointCount() > 0) {
        hash = (37 * hash) + ENDPOINT_FIELD_NUMBER;
        hash = (53 * hash) + getEndpointList().hashCode();
      }
      if (hasSiloId()) {
        hash = (37 * hash) + SILOID_FIELD_NUMBER;
        hash = (53 * hash) + getSiloId();
      }
      if (hasRound()) {
        hash = (37 * hash) + ROUND_FIELD_NUMBER;
        hash = (53 * hash) + getRound();
      }
      if (hasIndex()) {
        hash = (37 * hash) + INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getIndex();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ada.federate.rpc.RPCService.HelloRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ada.federate.rpc.RPCService.HelloRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ada.federate.rpc.RPCService.HelloRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ada.federate.rpc.RPCService.HelloRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ada.federate.rpc.RPCService.HelloRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ada.federate.rpc.RPCService.HelloRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ada.federate.rpc.RPCService.HelloRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ada.federate.rpc.RPCService.HelloRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ada.federate.rpc.RPCService.HelloRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ada.federate.rpc.RPCService.HelloRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ada.federate.rpc.RPCService.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ada.federate.rpc.RPCService.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ada.federate.rpc.RPCService.HelloRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code federate.HelloRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:federate.HelloRequest)
        com.ada.federate.rpc.RPCService.HelloRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ada.federate.rpc.RPCService.internal_static_federate_HelloRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ada.federate.rpc.RPCService.internal_static_federate_HelloRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ada.federate.rpc.RPCService.HelloRequest.class, com.ada.federate.rpc.RPCService.HelloRequest.Builder.class);
      }

      // Construct using com.ada.federate.rpc.RPCService.HelloRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        endpoint_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        siloId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        round_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        index_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ada.federate.rpc.RPCService.internal_static_federate_HelloRequest_descriptor;
      }

      @java.lang.Override
      public com.ada.federate.rpc.RPCService.HelloRequest getDefaultInstanceForType() {
        return com.ada.federate.rpc.RPCService.HelloRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ada.federate.rpc.RPCService.HelloRequest build() {
        com.ada.federate.rpc.RPCService.HelloRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ada.federate.rpc.RPCService.HelloRequest buildPartial() {
        com.ada.federate.rpc.RPCService.HelloRequest result = new com.ada.federate.rpc.RPCService.HelloRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          endpoint_ = endpoint_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.endpoint_ = endpoint_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.siloId_ = siloId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.round_ = round_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.index_ = index_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ada.federate.rpc.RPCService.HelloRequest) {
          return mergeFrom((com.ada.federate.rpc.RPCService.HelloRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ada.federate.rpc.RPCService.HelloRequest other) {
        if (other == com.ada.federate.rpc.RPCService.HelloRequest.getDefaultInstance()) return this;
        if (!other.endpoint_.isEmpty()) {
          if (endpoint_.isEmpty()) {
            endpoint_ = other.endpoint_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEndpointIsMutable();
            endpoint_.addAll(other.endpoint_);
          }
          onChanged();
        }
        if (other.hasSiloId()) {
          setSiloId(other.getSiloId());
        }
        if (other.hasRound()) {
          setRound(other.getRound());
        }
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSiloId()) {
          return false;
        }
        if (!hasRound()) {
          return false;
        }
        if (!hasIndex()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ada.federate.rpc.RPCService.HelloRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ada.federate.rpc.RPCService.HelloRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList endpoint_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureEndpointIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          endpoint_ = new com.google.protobuf.LazyStringArrayList(endpoint_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string endpoint = 1;</code>
       * @return A list containing the endpoint.
       */
      public com.google.protobuf.ProtocolStringList
          getEndpointList() {
        return endpoint_.getUnmodifiableView();
      }
      /**
       * <code>repeated string endpoint = 1;</code>
       * @return The count of endpoint.
       */
      public int getEndpointCount() {
        return endpoint_.size();
      }
      /**
       * <code>repeated string endpoint = 1;</code>
       * @param index The index of the element to return.
       * @return The endpoint at the given index.
       */
      public java.lang.String getEndpoint(int index) {
        return endpoint_.get(index);
      }
      /**
       * <code>repeated string endpoint = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the endpoint at the given index.
       */
      public com.google.protobuf.ByteString
          getEndpointBytes(int index) {
        return endpoint_.getByteString(index);
      }
      /**
       * <code>repeated string endpoint = 1;</code>
       * @param index The index to set the value at.
       * @param value The endpoint to set.
       * @return This builder for chaining.
       */
      public Builder setEndpoint(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEndpointIsMutable();
        endpoint_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string endpoint = 1;</code>
       * @param value The endpoint to add.
       * @return This builder for chaining.
       */
      public Builder addEndpoint(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEndpointIsMutable();
        endpoint_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string endpoint = 1;</code>
       * @param values The endpoint to add.
       * @return This builder for chaining.
       */
      public Builder addAllEndpoint(
          java.lang.Iterable<java.lang.String> values) {
        ensureEndpointIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, endpoint_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string endpoint = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndpoint() {
        endpoint_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string endpoint = 1;</code>
       * @param value The bytes of the endpoint to add.
       * @return This builder for chaining.
       */
      public Builder addEndpointBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEndpointIsMutable();
        endpoint_.add(value);
        onChanged();
        return this;
      }

      private int siloId_ ;
      /**
       * <code>required int32 siloId = 2;</code>
       * @return Whether the siloId field is set.
       */
      @java.lang.Override
      public boolean hasSiloId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 siloId = 2;</code>
       * @return The siloId.
       */
      @java.lang.Override
      public int getSiloId() {
        return siloId_;
      }
      /**
       * <code>required int32 siloId = 2;</code>
       * @param value The siloId to set.
       * @return This builder for chaining.
       */
      public Builder setSiloId(int value) {
        bitField0_ |= 0x00000002;
        siloId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 siloId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSiloId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        siloId_ = 0;
        onChanged();
        return this;
      }

      private int round_ ;
      /**
       * <code>required int32 round = 5;</code>
       * @return Whether the round field is set.
       */
      @java.lang.Override
      public boolean hasRound() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 round = 5;</code>
       * @return The round.
       */
      @java.lang.Override
      public int getRound() {
        return round_;
      }
      /**
       * <code>required int32 round = 5;</code>
       * @param value The round to set.
       * @return This builder for chaining.
       */
      public Builder setRound(int value) {
        bitField0_ |= 0x00000004;
        round_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 round = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRound() {
        bitField0_ = (bitField0_ & ~0x00000004);
        round_ = 0;
        onChanged();
        return this;
      }

      private int index_ ;
      /**
       * <pre>
       * 密钥生成
       *  required string p = 5;
       *  required string g = 6;
       *  required string publicKey = 7;
       * </pre>
       *
       * <code>required int32 index = 6;</code>
       * @return Whether the index field is set.
       */
      @java.lang.Override
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 密钥生成
       *  required string p = 5;
       *  required string g = 6;
       *  required string publicKey = 7;
       * </pre>
       *
       * <code>required int32 index = 6;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return index_;
      }
      /**
       * <pre>
       * 密钥生成
       *  required string p = 5;
       *  required string g = 6;
       *  required string publicKey = 7;
       * </pre>
       *
       * <code>required int32 index = 6;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        bitField0_ |= 0x00000008;
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 密钥生成
       *  required string p = 5;
       *  required string g = 6;
       *  required string publicKey = 7;
       * </pre>
       *
       * <code>required int32 index = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        index_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:federate.HelloRequest)
    }

    // @@protoc_insertion_point(class_scope:federate.HelloRequest)
    private static final com.ada.federate.rpc.RPCService.HelloRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ada.federate.rpc.RPCService.HelloRequest();
    }

    public static com.ada.federate.rpc.RPCService.HelloRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HelloRequest>
        PARSER = new com.google.protobuf.AbstractParser<HelloRequest>() {
      @java.lang.Override
      public HelloRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ada.federate.rpc.RPCService.HelloRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_federate_HelloRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_federate_HelloRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\010federate\032\014common.proto\"" +
      "N\n\014HelloRequest\022\020\n\010endpoint\030\001 \003(\t\022\016\n\006sil" +
      "oId\030\002 \002(\005\022\r\n\005round\030\005 \002(\005\022\r\n\005index\030\006 \002(\0052" +
      "\241\005\n\005SeJam\0224\n\010rpcHello\022\026.federate.HelloRe" +
      "quest\032\020.federate.Status\022>\n\npubicQuery\022\027." +
      "federate.SQLExpression\032\025.federate.QueryR" +
      "esult\"\000\022T\n\033groupByAggregationPlaintext\022\034" +
      ".federate.PublicQueryMessage\032\025.federate." +
      "FinalResult\"\000\022@\n\020groupByPlaintext\022\027.fede" +
      "rate.SQLExpression\032\021.federate.GroupIR\"\000\022" +
      "9\n\ngroupByADD\022\027.federate.SQLExpression\032\020" +
      ".federate.Status\"\000\022<\n\014groupByORDER\022\027.fed" +
      "erate.SQLExpression\032\021.federate.GroupIR\"\000" +
      "\022B\n\016aggregationADD\022\027.federate.SQLExpress" +
      "ion\032\025.federate.FinalResult\"\000\022>\n\020aggregat" +
      "ionORDER\022\027.federate.SQLExpression\032\017.fede" +
      "rate.RawIR\"\000\022B\n\025encryptedAggregateADD\022\017." +
      "federate.RawIR\032\026.federate.AggregatedIR\"\000" +
      "\022I\n\026decryptAggregatedORDER\022\026.federate.Ag" +
      "gregatedIR\032\025.federate.FinalResult\"\000B$\n\024c" +
      "om.ada.federate.rpcB\nRPCServiceP\000"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ada.federate.rpc.RPCCommon.getDescriptor(),
        });
    internal_static_federate_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_federate_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_federate_HelloRequest_descriptor,
        new java.lang.String[] { "Endpoint", "SiloId", "Round", "Index", });
    com.ada.federate.rpc.RPCCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
